### PR TITLE
Update map report count when report is canceled

### LINKED ISSUE #306: Map is still showing in "Show only with reports" filter when report is filed and then canceled
My python knowledge is quite limited (i.e. haven't ever seen python code before), but supposedly I'm onto something here:

This is the POST for map report which creates new Report object, pushes that reports container and increments map's "amount_reports" value
https://github.com/OpenRA/OpenRA-Resources/blob/a3c053b46e0ec99a7a40bf5adb40565b71f0c8e9/openra/views.py#L401-L420

This is the "cancelReport" action which removes the Report object specified. Note, however, that "amount_reports" is not decremented.
https://github.com/OpenRA/OpenRA-Resources/blob/a3c053b46e0ec99a7a40bf5adb40565b71f0c8e9/openra/views.py#L1011-L1015

"Only show with reports" filter uses the "amount_reports" field here
https://github.com/OpenRA/OpenRA-Resources/blob/db42f5b617a3a1d6729676aeb6a83a2031dea9f0/openra/misc.py#L406-L408

### PR DESCRIPTION
**Pull request by netnazgul**
Supposedly fixes #306

If it works, existing maps with incorrect non-zero "amount_reports" attribute need to be updated manually in the database.

### CODE REVIEW

**Comment by netnazgul** [comment]
another issue this pr fixes is that maps that were reported >2 times will have big red "ATTENTION" banner even if they don't have active reports. `amount_reports` is used in html checks whereas in python code `Reports` container is polled like this:
https://github.com/OpenRA/OpenRA-Resources/blob/6f601d98ad0fe5c3adfc98d14a420db50dbaa5b8/openra/api.py#L237-L238

**Comment by dsimmons87** [comment]
I was able to reproduce the original problem, and this fix works fine for me.

I guess ideally the hard coded amount_reports variable shouldn't exist, and a proper relationship should be set up between Maps and Reports, but that would involve a lot more changes, and this fixes the problem (other than updating the database).

**Comment by dsimmons87** [comment]
Also with regards to updating existing records, does this SQL look ok:

```
UPDATE openra_maps
SET amount_reports = (
	SELECT COUNT(*) FROM openra_reports WHERE ex_id = openra_maps.id
);
```

I tested it on my local version and it updated correctly there, but I thought I should post it here too to check in case there is something I've missed.

**Comment by dsimmons87** [comment]
Ok, this has now been deployed and the SQL above run.

**Pull request merged**
